version: '3.8'
services:
  dashboardism:
    image: noahquint/dashboardism
    container_name: dashboardism
    ports: ["10.0.2.132:8081:8081"]
    environment:
      - baseurl=microservism:5000
    #volumes: [/var/run/docker.sock:/var/run/docker.sock]  # Nodig om containers/images aan te kunnen spreken
  microservism:
    image: noahquint/microservism
    container_name: microservism
    ports: ["5000:5000"]
    volumes: [/var/run/docker.sock:/var/run/docker.sock]  # Nodig om containers/images aan te kunnen spreken
